ttle: Qing Yao
url: "https://dounick.github.io"
remote_theme: ankitsultana/researcher@gem
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

#footer: yes
#footer_url: "https://github.com/dounick"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "CV.pdf"
 - name: "Contact"
   link: "google.com"
